default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coaching_platform_development
  username: coaching_platform
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: coaching_platform_test

production:
  <<: *default
  database: coaching_platform_production
  username: coaching_platform
  password: <%= ENV['COACHING_PLATFORM_DATABASE_PASSWORD'] %>
